### ISSUE TITLE
S3 support for Flink

### ISSUE THREAD

**Issue by henneberger** [DataSQRL/sqrl#425]
Adds S3 support to Flink. This will use the s3-presto plugin and will use the flink plugin system. 

For more information about flink's plugin system, see [https://nightlies.apache.org/flink/flink-docs-stable/docs/deployment/filesystems/plugins/](https://nightlies.apache.org/flink/flink-docs-stable/docs/deployment/filesystems/plugins/)

To use S3 over aws using access keys (as opposed to IAM), you will need to configure your token by either flink configuration or through environmental variables. Otherwise, you'll receive a stacktrace like the one below:

```
Fail to retrieve token
deploy-flink-jobmanager-1     | com.amazonaws.SdkClientException: Failed to connect to service endpoint:
deploy-flink-jobmanager-1     | 	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:165) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.getCredentials(EC2ContainerCredentialsProviderWrapper.java:75) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
deploy-flink-jobmanager-1     | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1257) ~[flink-s3-fs-presto-1.16.1.jar:1.16.1]
```

To configure in docker compose, add your aws tokens to the docker-compose.yaml script:

```

  flink-jobmanager:
    image: flink:1.16.1-scala_2.12-java11
    ports:
      - "8081:8081"
    command: /bin/bash /exec/init-flink.sh jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
      - AWS_ACCESS_KEY_ID=MYAWSACCESSKEY
      - AWS_SECRET_KEY=MYAWSSECRETKEY
    volumes:
      - ./init-flink.sh:/exec/init-flink.sh
      - /Users/henneberger/helm/conference:/build

  flink-taskmanager:
    image: flink:1.16.1-scala_2.12-java11
    depends_on:
      - flink-jobmanager
    command: /bin/bash /exec/init-flink.sh taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 1
      - AWS_ACCESS_KEY_ID=MYAWSACCESSKEY
      - AWS_SECRET_KEY=MYAWSSECRETKEY
    volumes:
      - ./init-flink.sh:/exec/init-flink.sh

```
