### ISSUE TITLE
Timestamp field is null when reading from Kafka

### ISSUE THREAD

**Issue by nandorsoma** [DataSQRL/sqrl#722]
When trying to read this entity from Kafka, the timestamp field will be null in the resulting snapshot:
```json
{
  "id": 0,
  "epoch_timestamp": 1721054790,
  "some_value": "abc",
  "timestamp": "1970-01-20T22:04:14.790Z"
}
```
Using this schema and table.json:
```
name: "data"
schema_version: "1"
partial_schema: false
columns:
- name: "id"
  type: "BIGINT"
  tests:
  - "not_null"
- name: "epoch_timestamp"
  type: "BIGINT"
  tests:
    - "not_null"
- name: "some_value"
  type: "STRING"
  tests:
    - "not_null"
- name: "timestamp"
  type: "TIMESTAMP"
```
```
{
  "version": 1,
  "flink" : {
    "connector" : "kafka",
    "topic": "data_2",
    "properties.bootstrap.servers": "kafka:9092",
    "scan.startup.mode": "earliest-offset",
    "format" : "flexible-json"
  },
  "table" : {
    "type" : "source",
    "primary-key" : ["id"],
    "timestamp" : "timestamp",
    "watermark-millis" : "1"
  }
}
```
