### ISSUE TITLE
Flink Comparison functions `LIKE` and `Similar To` don't work with DataSQRL Strings

### ISSUE THREAD

**Issue by Zesky665** [DataSQRL/sqrl#949]
Data with the String type can't be used with `LIKE` and `SIMILAR TO` functions. 

For example:
```
LikeTest := SELECT id,
                   word LIKE '%al' AS like_word,
            FROM  UnmodifiedTextData
            ORDER BY id;
```
Where 
```
---
name: "strings"
schema_version: "1"
partial_schema: false
columns:
  - name: "id"
    type: "BIGINT"
    tests:
      - "not_null"
  - name: "word"
    type: "String"
    tests:
      - "not_null"
```

Throws this error
```
[FATAL] From line 42, column 20 to line 42, column 30: No match found for function signature LIKE
in script:<script> [42:20]:
/*+ test */
 LikeTest := SELECT id,
                   word LIKE '%al' AS like_word,
-------------------^

```
